RGBLIGHT_ENABLE = no
COMMAND_ENABLE = no
KEY_LOCK_ENABLE = yes
TAP_DANCE_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = yes
AUTO_SHIFT_ENABLE = no
MOUSEKEY_ENABLE = no

COMBO_ENABLE = yes

SRC += features/caps_word.c
